// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEcWn4aOGG_pPmMyS1etR5LkgIMhI_2Nk',
    appId: '1:384327137303:web:17a0d95ed91c5586ebc452',
    messagingSenderId: '384327137303',
    projectId: 'financemanager-d7990',
    authDomain: 'financemanager-d7990.firebaseapp.com',
    storageBucket: 'financemanager-d7990.firebasestorage.app',
    measurementId: 'G-H18QVTEEW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH5ApbBjg_pn7jmqnp5S4FFlPHjgNBFFU',
    appId: '1:384327137303:android:0633b611a8e3ad68ebc452',
    messagingSenderId: '384327137303',
    projectId: 'financemanager-d7990',
    storageBucket: 'financemanager-d7990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAihSG17zB_B-wD7FcPe3IUsyajRpDZ6yk',
    appId: '1:384327137303:ios:545f53482acd23d2ebc452',
    messagingSenderId: '384327137303',
    projectId: 'financemanager-d7990',
    storageBucket: 'financemanager-d7990.firebasestorage.app',
    iosBundleId: 'com.example.financemanageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAihSG17zB_B-wD7FcPe3IUsyajRpDZ6yk',
    appId: '1:384327137303:ios:545f53482acd23d2ebc452',
    messagingSenderId: '384327137303',
    projectId: 'financemanager-d7990',
    storageBucket: 'financemanager-d7990.firebasestorage.app',
    iosBundleId: 'com.example.financemanageapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEcWn4aOGG_pPmMyS1etR5LkgIMhI_2Nk',
    appId: '1:384327137303:web:69a0269669d683caebc452',
    messagingSenderId: '384327137303',
    projectId: 'financemanager-d7990',
    authDomain: 'financemanager-d7990.firebaseapp.com',
    storageBucket: 'financemanager-d7990.firebasestorage.app',
    measurementId: 'G-JXG23YY6LQ',
  );
}
